replicas:
  max: 5
  min: 2
image:
  repository: 192.168.68.108:5000/music-stream-ui
  tag: 1.12.0
  pullPolicy: Always
service:
  type: NodePort
  externalPort: 80
  internalPort: 80
  name: music-stream-ui
