replicas:
  max: 5
  min: 2
image:
  repository: 192.168.1.15:5000/music-stream-ui
  tag: 1.11.6
  pullPolicy: Always
service:
  type: NodePort
  externalPort: 80
  internalPort: 80
  name: music-stream-ui
